### ISSUE TITLE
Creating a new entity of type `hostile` creates an incorrect spawn egg lang entry

### ISSUE THREAD

**Issue by JosiahDZD** [DauntlessStudio/Bedrock-Developments#19]
I ran the command `bed new entity -t hostile -c --no-geo --no-texture ldz:new_dragon`, and this is the lang entry it created. It's just missing `.entity` after `item.spawn_egg`.
It should probably have the word `Spawn` in front of `New Dragon` as well
![image](https://github.com/DauntlessStudio/Bedrock-Developments/assets/107638265/76c00be7-09b9-4011-8b10-7883d798d1a7)

**Comment by DauntlessStudio** [comment]
This issue no longer applies to v3.0.0+
